                        <article>
                            <section>
                                <div class="wrapper border-box">
                                    <h1 class="mega sbu-3d-shadow"><span class="red">SBU</span> <span class="darker">Header</span><span class="grey">! Special h1</span></h1>
                                    <h1><span class="red">SBU Header! I am a red h1</span></h1>
                                    <h2><span class="darker">SBU Header! I am a darker h2</span></h2>
                                    <h3><span class="grey">SBU Header! I am a grey h3</span></h3>
                                    <h4>SBU Header! I am a h4</h4>
                                    <div class="subtitle">SBU Header! I am a subtitle</div>
                                    <h1 class="serif"><span class="red">Economic Development</span></h1>
                                    <h2 class="serif">Economic Development</h2>
                                    <h3 class="serif"><span class="grey">Economic Development</span></h3>
                                    <h1 class="sbu-3d-shadow" id="fittextdemo">Squeeze with FitText</h1>
                                    <p class="sbu-text sbu-text-shadow">From its beginnings a half-century ago, Stony Brook University has been characterized by <a href="#">innovation, energy, and progress, transforming the lives of people</a> who earn degrees, work, and make groundbreaking discoveries here. A <a href="#">dramatic trajectory</a> of growth has turned what was once a small teacher preparation college into an internationally recognized research institution that is <a class="external-link" href="#">changing</a> the world.</p>
                                    <p class="sbu-text sbu-text-shadow">From its beginnings a half-century ago, Stony Brook University has been characterized by <a href="#">innovation, energy, and progress, transforming the lives of people</a> who earn degrees, work, and make groundbreaking discoveries here. A <a href="#">dramatic trajectory</a> of growth has turned what was once a small teacher preparation college into an internationally recognized research institution that is <a class="external-link" href="#">changing</a> the world.</p>
                                    <p class="sbu-text sbu-text-shadow">From its beginnings a half-century ago, Stony Brook University has been characterized by <a href="#">innovation, energy, and progress, transforming the lives of people</a> who earn degrees, work, and make groundbreaking discoveries here. A <a href="#">dramatic trajectory</a> of growth has turned what was once a small teacher preparation college into an internationally recognized research institution that is <a class="external-link" href="#">changing</a> the world.</p>
                                    <p class="sbu-text sbu-text-shadow">From its beginnings a half-century ago, Stony Brook University has been characterized by <a href="#">innovation, energy, and progress, transforming the lives of people</a> who earn degrees, work, and make groundbreaking discoveries here. A <a href="#">dramatic trajectory</a> of growth has turned what was once a small teacher preparation college into an internationally recognized research institution that is <a class="external-link" href="#">changing</a> the world.</p>
                                    <p class="sbu-text sbu-text-shadow">From its beginnings a half-century ago, Stony Brook University has been characterized by <a href="#">innovation, energy, and progress, transforming the lives of people</a> who earn degrees, work, and make groundbreaking discoveries here. A <a href="#">dramatic trajectory</a> of growth has turned what was once a small teacher preparation college into an internationally recognized research institution that is <a class="external-link" href="#">changing</a> the world.</p>
                                    <p class="sbu-text sbu-text-shadow">From its beginnings a half-century ago, Stony Brook University has been characterized by <a href="#">innovation, energy, and progress, transforming the lives of people</a> who earn degrees, work, and make groundbreaking discoveries here. A <a href="#">dramatic trajectory</a> of growth has turned what was once a small teacher preparation college into an internationally recognized research institution that is <a class="external-link" href="#">changing</a> the world.</p>
                                </div>
                            </section>
                        </article>